// Regenerates dijkstra_maze_web/export-data.js from the REAL student/ tree.
//
// export-data.js is the splice BASE for the "Download my project" feature in
// app.js: the original starter files byte-for-byte, plus one marker record
// per TODO part so app.js knows where to paste a student's code back in.
// It holds no reference answers - only marker text and indentation, both of
// which are already visible to students in their own files.
//
// The previous generator lived in a throwaway scratch folder and was lost
// with that session (see HANDOFF.md); this is the re-derived, committed
// version. Re-run it whenever a student/*.py file changes:
//
//   node scripts/gen_export_data.js
//
// Marker format in the .py files:
//   # --- TODO 3: WRITE YOUR CODE BELOW ---   /   # --- END OF TODO 3 ---
// Bonus sub-steps use a hyphenated id (they are standalone steps now, not
// parts of a bigger one):
//   # --- TODO 8-2: WRITE YOUR CODE BELOW ---  /  # --- END OF TODO 8-2 ---
// The (Part n/m) form survives only for TODO 5, the one Required step that
// is still genuinely two coupled halves of a single expression.
"use strict";

const fs = require("fs");
const path = require("path");

const WEB = path.join(__dirname, "..");
const STUDENT = path.join(WEB, "..", "dijkstra_maze", "student");

// Order matters: it is the order the download writes the files in.
const FILE_ORDER = [
  "settings.py", "game.py", "player.py", "maze.py", "pathfinding.py",
  "cell.py", "goal.py", "items.py", "main.py", "requirements.txt",
];

const BEGIN_RE = /^([ \t]*)#\s*---\s*TODO\s+(\d+(?:-\d+)?)(?:\s*\(Part\s+(\d+)\/(\d+)\))?\s*:\s*WRITE YOUR CODE BELOW\s*---\s*$/;
const END_RE = /^[ \t]*#\s*---\s*END OF TODO\s+(\d+(?:-\d+)?)(?:\s*\(Part\s+(\d+)\/(\d+)\))?\s*---\s*$/;

function readFileLF(p) {
  return fs.readFileSync(p, "utf8").replace(/\r\n/g, "\n");
}

const files = {};
const markers = [];
const problems = [];

FILE_ORDER.forEach(function (name) {
  const full = path.join(STUDENT, name);
  if (!fs.existsSync(full)) { problems.push("missing source file: " + name); return; }
  const text = readFileLF(full);
  files[name] = text;

  const lines = text.split("\n");
  let open = null;
  lines.forEach(function (line, i) {
    const b = line.match(BEGIN_RE);
    if (b) {
      if (open) problems.push(name + ":" + (i + 1) + " a TODO marker opened while another was still open");
      open = {
        indent: b[1],
        id: b[2],
        // partIndex is 0-based; a single-part TODO records null.
        partIndex: b[3] ? parseInt(b[3], 10) - 1 : null,
        begin: line.trim(),
        total: b[4] ? parseInt(b[4], 10) : null,
      };
      return;
    }
    const e = line.match(END_RE);
    if (e) {
      if (!open) { problems.push(name + ":" + (i + 1) + " END marker with no matching begin"); return; }
      if (e[1] !== open.id) problems.push(name + ":" + (i + 1) + " END TODO " + e[1] + " closes TODO " + open.id);
      const endPart = e[2] ? parseInt(e[2], 10) - 1 : null;
      if (endPart !== open.partIndex) problems.push(name + ":" + (i + 1) + " END part " + e[2] + " closes part " + (open.partIndex === null ? "-" : open.partIndex + 1));
      markers.push([open.id, name, open.partIndex, open.indent, open.begin, line.trim()]);
      open = null;
    }
  });
  if (open) problems.push(name + ": TODO " + open.id + " was never closed");
});

// Every marker's begin/end text must be findable in its file (app.js splices
// on exactly these strings) and must be unique, or the splice would target
// the wrong block.
markers.forEach(function (m) {
  const src = files[m[1]] || "";
  [m[4], m[5]].forEach(function (needle) {
    const count = src.split(needle).length - 1;
    if (count !== 1) problems.push(m[1] + ": marker text appears " + count + " times: " + needle);
  });
});

if (problems.length) {
  console.error("REFUSING TO WRITE — marker problems found:");
  problems.forEach(function (p) { console.error("  - " + p); });
  process.exit(1);
}

const out = [
  '"use strict";',
  "",
  "// export-data.js -- pure content: the ORIGINAL student/ starter files",
  "// (byte-for-byte, generated from the real student/ tree) plus marker",
  "// metadata (file/indent/begin/end) for every TODO. This is the splice",
  "// BASE for the Python-export feature in app.js. It intentionally holds",
  "// no reference answers and no todos.json content beyond marker text and",
  "// indentation, which are already visible to students in their own files.",
  "//",
  "// GENERATED by scripts/gen_export_data.js -- do not edit by hand.",
  "var EXPORT_FILES = {",
  FILE_ORDER.filter(function (n) { return files[n] !== undefined; })
    .map(function (n) { return "  " + JSON.stringify(n) + ": " + JSON.stringify(files[n]) + ","; })
    .join("\n"),
  "};",
  "",
  "// Each entry: [stepId, file, partIndex(or null), indent, beginMarker, endMarker]",
  "var EXPORT_MARKERS = [",
  markers.map(function (m) {
    return "  [\n" + m.map(function (v) { return "    " + JSON.stringify(v); }).join(",\n") + "\n  ]";
  }).join(",\n"),
  "];",
  "",
  "window.EXPORT_DATA = { EXPORT_FILES: EXPORT_FILES, EXPORT_MARKERS: EXPORT_MARKERS };",
  "",
].join("\n");

fs.writeFileSync(path.join(WEB, "export-data.js"), out, "utf8");
console.log("export-data.js written: " + Object.keys(files).length + " files, " + markers.length + " markers");
const byStep = {};
markers.forEach(function (m) { byStep[m[0]] = (byStep[m[0]] || 0) + 1; });
console.log("  parts per TODO: " + Object.keys(byStep).sort().map(function (k) { return k + "=" + byStep[k]; }).join(" "));
